apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: recurring-task-events-sub
spec:
  topic: task-events
  routes:
    default: /events/task-events
  pubsubname: todo-pubsub
scopes:
  - recurring-task-service
